stages:
  - build
  - deploy


variables:
  #https://books.sonatype.com/mvnref-book/reference/running-sect-options.html#running-sect-batch-option
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

build-frontend:
  image: node:gallium-alpine
  stage: build
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    paths:
      - dist
  cache:
    paths:
      - node_modules/
      - .yarn

maven-gitlab-deploy:
  image: maven:3.6-jdk-8
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy -U
  artifacts:
    paths:
      - target/*.jar
  cache:
    key: ${CI_PROJECT_NAME}
    paths:
      - .m2/repository
  only:
    - system/gitlab

